function garmin = importgarmin(filename, dataLines)
%IMPORTFILE Import data from a text file
%  GARMIN = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  GARMIN = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  garmin = importfile("/Users/mmls8/OneDrive - Loughborough University/eBike/Cargo Bike Test/Joe&Alex/20200316/Joe_Off_40kg/processed/joe_off_40kg.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Mar-2020 11:25:34

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["timestamp", "position_lat", "position_long", "altitude", "speed", "distance", "power", "temperature", "date"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "datetime"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "date", "InputFormat", "yyyy-MM-dd HH:mm:ss");

% Import the data
garmin = readtable(filename, opts);

end